"""Phase 48 Chromium/WebGL verification of the original game's visual signal bridge.

Summon event is generated by a real lawful native placement. Hit/heal animation
plumbing is checked separately using the legacy visual() helper, explicitly as
signal fixtures rather than claimed as successful combat actions.
"""
from pathlib import Path
from functools import partial
from http.server import ThreadingHTTPServer,SimpleHTTPRequestHandler
import threading
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
server=ThreadingHTTPServer(('127.0.0.1',0),partial(SimpleHTTPRequestHandler,directory=str(ROOT)))
threading.Thread(target=server.serve_forever,daemon=True).start()
try:
  with sync_playwright() as pw:
    args={'headless':True,'args':['--no-sandbox','--enable-webgl','--use-gl=angle',
      '--use-angle=swiftshader','--enable-unsafe-swiftshader']}
    if Path('/usr/bin/chromium').exists():args['executable_path']='/usr/bin/chromium'
    browser=pw.chromium.launch(**args)
    page=browser.new_page(viewport={'width':1920,'height':1080})
    errors=[];page.on('pageerror',lambda exc:errors.append(str(exc)))
    page.add_init_script('''() => {
      let seed=Number(new URLSearchParams(location.search).get('qa_seed'))||198704;
      Math.random=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;};
    }''')
    url=f'http://127.0.0.1:{server.server_port}/Marorong_Card_War_Phase48_3D_Prototype.html'
    for seed in range(198704,198728):
      page.goto(url+f'?qa_seed={seed}')
      page.locator('#newGame').click();page.locator('#launchGame').click()
      page.get_by_role('button',name='이 손패로 시작').click()
      choices=page.locator('.hand-slot').evaluate_all('''els=>els.map((e,i)=>({
        i,cost:Number(e.querySelector('.cost-bubble')?.textContent||99),
        board:/type-(몬스터|시설|영웅유닛)/.test(e.querySelector('.card-ui')?.className||'')
      }))''')
      affordable=[v for v in choices if v['board'] and v['cost']<=2]
      if affordable:break
    assert affordable
    page.locator('.hand-slot').nth(affordable[0]['i']).evaluate('(e)=>e.click()')
    key=page.locator('#arena .slot.legal').first.get_attribute('data-slot')
    assert key
    page.locator('#mrr-battlefield-open').click()
    page.wait_for_function('MRRBattlefield.state.open && MRRBattlefield.state.scene.frames>3',timeout=20000)
    state=page.evaluate('MRRBattlefield.state.scene')
    assert state['revision']>=48 and state['nativeFxRevision']==48,state
    assert state['fxSources']=='native-slot-classes',state
    assert state['fxReceived']=={'hit':0,'heal':0,'summon':0},state
    location=page.evaluate('(key)=>MRRBattlefield.scene.projectSlot(key)',key)
    page.mouse.click(location['x'],location['y'])
    page.wait_for_function('MRRBattlefield.state.scene.fxReceived.summon>=1',timeout=8000)
    assert page.locator('#arena [data-slot="'+key+'"] .board-card').count()==1
    assert page.evaluate('MRRBattlefield.state.scene.liveFxCount')>=1
    page.screenshot(path=str(ROOT/'tests/phase48_real_native_summon_fhd.png'))
    page.wait_for_function('MRRBattlefield.state.scene.liveFxCount===0',timeout=7000)
    before=page.evaluate('''() => {let s=gameSnapshot();delete s.storedAt;return JSON.stringify(s)}''')
    # Verify visual-only hit/heal signals independently, without pretending an
    # actual combat transaction happened. These call the original visual helper.
    for event in ['hit','heal']:
      page.evaluate('''([event,key]) => {
        const [owner,row,col]=key.split(':');
        visual(event,Number(owner),row,Number(col));
      }''',[event,key])
      page.wait_for_function('(kind)=>MRRBattlefield.state.scene.fxReceived[kind]>=1',arg=event,timeout=7000)
      assert page.evaluate('MRRBattlefield.state.scene.liveFxCount')>=1
      page.screenshot(path=str(ROOT/f'tests/phase48_{event}_signal_fixture.png'))
      page.wait_for_function('MRRBattlefield.state.scene.liveFxCount===0',timeout=7000)
    assert before==page.evaluate('''() => {let s=gameSnapshot();delete s.storedAt;return JSON.stringify(s)}''')
    for width,height in [(1366,768),(390,844)]:
      page.set_viewport_size({'width':width,'height':height})
      page.wait_for_timeout(350)
      assert page.locator('#mrr-battlefield-stage canvas').evaluate('e=>e.width>100 && e.height>100')
      page.screenshot(path=str(ROOT/f'tests/phase48_battlefield_{width}x{height}.png'))
    page.locator('#mrr-battlefield-close').click()
    assert page.evaluate('MRRBattlefield.scene===null')
    assert not page.evaluate('MRRBattlefield.state.open')
    assert not errors,errors
    print('PHASE48 PASS - real native summon, separately labeled native visual-signal fixtures hit/heal, GPU FX release, 3 viewport WebGL, unchanged gameplay during visual effects')
    browser.close()
finally:
  server.shutdown();server.server_close()
